//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Hiring_Sys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_EmployeeHiringEntities1 : DbContext
    {
        public db_EmployeeHiringEntities1()
            : base("name=db_EmployeeHiringEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_education> tbl_education { get; set; }
        public virtual DbSet<tbl_experience> tbl_experience { get; set; }
        public virtual DbSet<tbl_personal_info> tbl_personal_info { get; set; }
        public virtual DbSet<tbl_projects> tbl_projects { get; set; }
    }
}
