//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Hiring_Sys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_experience
    {
        public int exper_id { get; set; }
        public int member_id { get; set; }

        [Required(ErrorMessage = "Company Name is Required")]
        [DisplayName("Company Name")]
        public string company { get; set; }

        [Required(ErrorMessage = "Start Date is Required")]
        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Starts_date { get; set; }

        [Required(ErrorMessage = "End Date is Required")]
        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> end_date { get; set; }

        [Required(ErrorMessage = "Experience time is Required")]
        [DisplayName("Experience")]
        public string experience_time { get; set; }

        [Required(ErrorMessage = "Position is Required")]
        [DisplayName("Position")]
        public string position { get; set; }
    
        public virtual tbl_personal_info tbl_personal_info { get; set; }
    }
}
