//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Hiring_Sys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_personal_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_personal_info()
        {
            this.tbl_category = new HashSet<tbl_category>();
            this.tbl_education = new HashSet<tbl_education>();
            this.tbl_experience = new HashSet<tbl_experience>();
            this.tbl_projects = new HashSet<tbl_projects>();
        }
    
        public int member_id { get; set; }
        public string firsst_name { get; set; }
        public string last_name { get; set; }
        public string UserName { get; set; }
        public string email { get; set; }
        public string cnt_no { get; set; }
        public string h_add { get; set; }

        [DataType(DataType.Password)]
        public string Pass { get; set; }
        public string cnfpass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_category> tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_education> tbl_education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_experience> tbl_experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_projects> tbl_projects { get; set; }
    }
}
