//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Hiring_Sys.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tbl_projects
    {
        public int proj_id { get; set; }
        public int member_id { get; set; }
        public string proj_name { get; set; }
        public string languages { get; set; }
        public string image_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public virtual tbl_personal_info tbl_personal_info { get; set; }
    }
}
